# Generated by Django 2.2.4 on 2019-08-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BPM',
        ),
    ]
