# Generated by Django 2.2.4 on 2019-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_bpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFMC',
            fields=[
                ('customer_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Recency_flag', models.IntegerField()),
                ('Freq_flag', models.IntegerField()),
                ('monetary_flag', models.IntegerField()),
            ],
        ),
    ]
