# Generated by Django 2.2.4 on 2019-08-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rfmc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFM',
        ),
    ]
