# Generated by Django 2.2.4 on 2019-08-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('society_id', models.CharField(max_length=20)),
                ('city_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=20)),
                ('subcategory_id', models.CharField(max_length=20)),
                ('manufacturer_id', models.CharField(max_length=20)),
                ('selling_price_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subsciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('route_id', models.CharField(default=0, max_length=20)),
                ('store_id', models.CharField(max_length=20)),
                ('order_date', models.CharField(max_length=20)),
                ('product_quantity', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('product_added_to_basket_on', models.CharField(max_length=20)),
                ('subscription', models.BooleanField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Product')),
            ],
        ),
    ]
