# Generated by Django 2.2.4 on 2019-08-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPM',
            fields=[
                ('customer_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('r1', models.CharField(max_length=20)),
                ('r2', models.CharField(max_length=20)),
                ('r3', models.CharField(max_length=20)),
                ('r4', models.CharField(max_length=20)),
                ('r5', models.CharField(max_length=20)),
                ('r6', models.CharField(max_length=20)),
                ('r7', models.CharField(max_length=20)),
                ('r8', models.CharField(max_length=20)),
                ('r9', models.CharField(max_length=20)),
                ('r10', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Subsciption',
        ),
    ]
