# Generated by Django 2.2.4 on 2019-08-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_rfm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CP',
            fields=[
                ('customer_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Sub_flag', models.IntegerField()),
                ('subscription', models.BooleanField()),
                ('Recency_flag', models.IntegerField()),
                ('Refreq', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
