# Generated by Django 2.2.4 on 2019-08-04 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_cp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BPM',
        ),
        migrations.DeleteModel(
            name='CP',
        ),
        migrations.DeleteModel(
            name='RFM',
        ),
    ]
